akermu/emacs-libvterm

elisp.c
elisp.h
vterm-module.c
vterm-module.h
vterm.el

it works now .
and you can use C-v and M-v scroll the screen now without tmux and screen

trying support scrollback 

---

vterm.el

run hook vterm-exit-hook with  the term buffer as argument

---

vterm.el

make sure `package-lint` and  `checkdoc` is happy with the docstrings.
#53 
melpa/melpa#6133

supporting publish emacs-libvterm to Melpa.

---

vterm.el

check buffer-live-p in vterm--filter

---

elisp.c
elisp.h
vterm-module.c
vterm-module.h

Support blink cursor mode and set cursor type 

---

elisp.c
elisp.h
vterm-module.c

the buffer can  auto scroll   even the vterm window is not activated.

---

vterm-module.c
vterm.el

Add support for backtab

---

README.md
elisp.c
vterm-module.c
vterm.el

support vterm-copy-mode

---

README.md
elisp.c
elisp.h
vterm-module.c
vterm-module.h
vterm.el

Add directory tracking via OSC callback

---

README.md
vterm.el

Add remote directory tracking

---

vterm-module.c

Add support for the <next> key

---

README.md
vterm.el

Verify and clarify that vterm needs module support

---

README.md
vterm-module.c

https://github.com/akermu/emacs-libvterm/pull/112#issuecomment-519561616

change directory tracking prefix form 51; to 51;A

---

vterm.el

In case, you want to start vterm setting the buffer name.
Please let me know if there is anything we could do better.
Thanks in advance.

Add optional buffer name

---

README.md
vterm.el

Clarify colors in README and doctext

---

vterm-module.c

Add special handling for C-j

---

vterm.el

Before this PR: You need to set `vterm-keymap-exceptions` before the package is loaded.
After this PR: You can customize the variable even after the package is loaded, and the change will be effective without restarting Emacs or reloading the package.
Note: You can use either the customization interface or `general-setq` from [general.el](https://github.com/noctuid/general.el) to set the variable. Simply using `setq` won't work.

Allow customizing vterm-keymap-exceptions after loading the package

---

README.md

#144 was merged, the feature would be hard to discover if it is not mentioned anywhere.

Update README to reflect #144, and other small improvements

---

README.md

#137
and  supporting directory tracking for fish

update readme about directory tracking.

---

README.md
vterm.el

Prevents anyone that can potentially display characters in the terminal from taking over your editor.
For issue #182.

Replace eval with whitelist

---

vterm.el

add defcustom vterm-min-window-width.

---

vterm.el

fix #207 bind M- keys for terminal emacs.

---

README.md

make vterm support tmux and screen

---

README.md

Added discussions from the following issue https://github.com/akermu/emacs-libvterm/issues/216 to the README file

Added ubuntu installation notes

---

elisp.c
elisp.h
vterm-module.c
vterm-module.h

fix adjust_topline fix #222

---

elisp.c
elisp.h
vterm-module.c
vterm.el

this should fix #226 #198 ,and #222 is related

fix #226 #198 

---

README.md
vterm.el

Remove special default font and just use the default

---

elisp.h
vterm-module.c

fix #241 use :extend face property for emacs 27 and later

---

vterm.el

add vterm-check-proc 

---

vterm-module.c
vterm-module.h

Remove unused vars in vterm-module

---

vterm.el

fix (vterm--get-prompt-point) return nil when no prompt found

---

README.md
vterm-module.c
vterm.el

@condy0919 I added your PR #320 to the FAQ, what do you think?

Fix message passage for long commands, add more FAQs

---

vterm.el

Disable vterm-copy-mode outside vterm buffers

---

vterm.el

Send escape

---

README.md

- add vterm_cmd examples for fish shell to README.md
- also, change following line to make the transition clearer

add vterm_cmd examples for fish shell to README.md

---

vterm.el

avoid garbling of certain multibyte characters .

---

vterm.el

*BSD seems to have an issue (as discussed in https://github.com/akermu/emacs-libvterm/issues/242) where the iutf8 argument is not supported when starting stty.
This is a pretty gross work-around I came up with to alleviate the problem.
I tested this locally with OpenBSD, which also has this deficiency, and it seems to work.
Suggestions/feedback welcome.

[Fix] Gross hack to work around problem on *BSD

---

vterm.el

Disable all automatic fontification

---

vterm-module.c

Some emoji characters are composed by some other emoji characters with
zero width joiner, such as:
🏊🏻‍♀️
🏊🏻‍♂️
👩‍👩‍👧
👨‍👨‍👧‍👦
With this patch, these emoji characters can be correctly rendered by
https://bitbucket.org/mituharu/emacs-mac.

fix rendering of combining characters

---

README.md

Great project, thanks for this!
The patch just fixes typos and capitalization in the README

Fix typos and capitalization

---

vterm-module.c
vterm-module.h

Fixes https://github.com/akermu/emacs-libvterm/issues/499

Allow multiple commands between redraws

---

vterm.el

should fix #394 .
#408 #405 are related .
Need more tester before merged.

another try to avoid garbling of certain multibyte characters .

---

vterm.el

support creating ssh using docker-tramp by add vterm-tramp-shells.

---

vterm.el

Call vterm-copy-mode-done with the mandatory ARG argument

---

vterm-module.c
vterm.el

add option vterm-set-bold-hightbright

---

vterm.el

rewrite these functions with vterm--translate-event-to-args.
`vterm--translate-event-to-args` would translate EVENT as list of args for `vterm-send-key'.
so that vterm--self-insert/vterm-send/vterm-send-next-key could use it . 
When some input method is enabled, one key may generate
several characters, so the result of this function is a list,
looks like: ((\"m\" :shift ))"

rewrite vterm--self-insert/vterm-send/vterm-send-next-key.

---

vterm.el

from `vterm--self-insert`
fixes #639 
Thanks :pray:

Change a binding for S-prior back to `scroll-down-command`

---

vterm.el

- When checking for vterm-mode, also support modes derived from vterm

Support modes derived from vterm
