vterm-module.c
Thanks for tackling the integration of libvterm with emacs !
This PR should fix building the module on OSX, forkpty is available through util.h on OSX: http://www.unix.com/man-page/osx/3/forkpty/
A neater fix would be to start using autotools to build the module and in the configure phase set some ENV variables depending on the presence of one or the other lib on the OS, but this should do for now.
Test plan:
- Make on OSX => no errors, run vterm-create => terminal shows up
- Make on linux => no errors
=> Fix build on OSX

CMakeLists.txt
Otherwise the `Loading ...` messages will pollute the output.
=> add -Q option when printing emacs version

vterm.el
This one was surprising to me. Apparently list literals are only compiled once, so if you mutate them (with *nconc*) you get unexpected results.
```emacs-lisp
(setq a nil)
nil
(setq a (nconc '(a) a))
(a)
;; new list literal, so still expected results
(setq a (nconc '(a) a))
(a a)
;; re-use of the same list literal after being mutated
(dotimes (- 2) (setq a (nconc '(a) a)))
nil
a
(a a a a a . #2)  ;; circular list
```
After changing *nconc* to *append* you can run two vterms in the same Emacs session without it hanging.
Btw, happy to see you accepting PRs here. I'm excited for this initiative and if you don't mind I'll continue to fiddle with it.
=> Use append instead of nconc in vterm-mode

CMakeLists.txt
On some platforms, the location of libvterm headers and library are
not in standard places that gcc/clang looks for by default.
The usual practice is to use find_path/find_library and then
link them properly. In my particular case, this helps clang to
find homebrew-installed libvterm on OS X.
=> Use CMake library search to look for libvterm location

elisp.c, elisp.h, vterm-module.c, vterm-module.h, vterm.el
```
(defun vterm--auto-rename-buffer (title)
(rename-buffer (format "vterm %s" title)))
(add-hook 'vterm-set-title-hook 'vterm--auto-rename-buffer)
```
set terminal title dynamically to the current working directory
```
precmd() {
print -Pn "\e]0;%~ $1\a"
}
```
see http://tldp.org/HOWTO/Xterm-Title-4.html about how to set terminal title
for different shell.
=> support set terminal title .

README.md, vterm.el
Some improvement on the docs, including fixing a non-existing command on MacOS (`hombrew` -> `brew`).
=> improve docs

vterm.el
Now you can yank from Emacs and paste from your system's clipboard to your terminal 👌:sparkles: 
I agree that in principle, sending the chars one at a time might not be very optimised, but there is no function yet to send strings to vterm from Emacs, I don't know how to implement one, don't know the edge cases that there will be if I try to, don't really have the time for it, and it works quite well like this for now.
Happy yanking 😁
=> enable yanking (pasting from clipboard / kill-ring)

CMakeLists.txt, vterm.el
With the asynchronous compilation there would always be an error thrown on the `(require 'vterm-module)`, as there is no `vterm-module` before the compilation is done. Using `call-process` instead of `make-process` makes the compilation is synchronous, so the `(require 'vterm-module)` will only be called once it is finished.
There is also another fix: 38eaf28 (`Add CI`) broke the library's output directory and made `emacs-libvterm` unusable as Emacs was not able to find the library anymore.
I need this PR for integrating `emacs-libvterm` properly into Spacemacs (https://github.com/syl20bnr/spacemacs/pull/11552).
I also removed the `(pop-to-buffer buffer)` and `(delete-window window)`. The user doesn't need to see the compilation and it is awkward when you have your window layout and …
=> Fix auto-install

vterm.el
C-y being bound to Emac's yank, this allows using the terminal's own yank/paste and do combinations such as `C-a C-k` to kill the currently unsent command and `C-c C-y` to restore (paste) it.
=> bind terminal's C-y (yank/paste) to C-c C-y

vterm-module.c, vterm-module.h, vterm.el
I think should not call invalidate_terminal() in  term_resize
when the window heigh decreased, 
the value of term->invalid_end can't bigger than window height 
maybe this is related to #33
=> fix window resize and ignore black at end of line

vterm.el
My zsh config is based on env `INSIDE_EMACS` to alias things like: `vi=emacsclient`
=> Add env INSIDE_EMACS to vterm

elisp.c, elisp.h, vterm-module.c
this is necessary for emacs27 
it behave differently  between emacs-libvterm and iterm2 when I use zaw 
in iterm2  when I press ctrl-r it clear all screen and show the zaw candidates ,
but in emacs-libvterm ,the screen is not cleared(recentered) 
```
git clone  https://github.com/zsh-users/zaw
echo "source ${PWD}/zaw/zaw.zsh" >> ~/.zshrc
echo "  bindkey -M emacs '^R' zaw-history  # C-r" >> ~/.zshrc
```
=> fix recenter for emacs27

vterm.el
https://github.com/akermu/emacs-libvterm/issues/40
It's similar function `term-send-return` on https://www.emacswiki.org/emacs/download/multi-term.el.
It works well for me on FZF, Tmux inside Vterm.
=> Fix: enter/return does not always works

CMakeLists.txt, README.md, elisp.c, elisp.h, vterm-module.c, vterm-module.h, vterm.el
=> Support 256color

README.md
This commit fixes English typos, introduces spaces after commas, and colorize the `elisp` part of the README.
=> Improve punctiation, spacing and fix typos in README.md

vterm.el
This change will save the point when entering copy mode and restore it back once
leaving. This feels much nicer than having the point get out of sync with where
the terminal actually thinks it is.
If the creators of vterm know of a better way I would be glad to figure out how
to implement it, but for now this seems to work fine.
=> Save and restore point in copy mode.

vterm.el
(Straight package manager)[https://github.com/raxod502/straight.el] builds packages by symlinking files into a build dir and byte-compiling there. This confuses the library location code, but is easily fixed.
=> Support symlinked builds

vterm.el
On tmux, I was able to copy a selected text and finish the copy mode with enter/return key.
It would be convenient to have the same feature on vterm.el, so I implemented it.
=> Add vterm-copy-mode-done command

vterm.el
`vterm-yank-primary` is essentially the merger of `mouse-yank-primary` and `vterm-yank`. Select with the mouse, and paste in vterm with the central button (`<mouse-2>`).
=> Allow central mouse button to yank from primary selection

vterm.el
Directory tracking doesn't work as expected with `ivy-find-file`. This seems to be because `default-directory` does not end with `/`. Use `file-name-as-directory` to append a trailing delimiter to the path.
=> Append a trailing delimiter to the new value of default-directory

vterm.el
width should = window-width - line-num-width
~~don't known why `echo $COLUMNS` still  equals to `window-body-width`~~
ready to be reviewed
=> support display-line-numbers-mode.

README.md, elisp.c, elisp.h, vterm-module.c, vterm-module.h, vterm.el
#161 
eval 
```
(message (buffer-name))
``` 
by 
```sh
echo -n  "\e]51;E(message (buffer-name))\e\\";
```
=> Support sending Elisp Command to Emacs Buffer

README.md, vterm-module.c, vterm-module.h, vterm.el
#165 
libvterm does not support clear scrollback directly.
`vterm-clear-scrollback` is bind on `C-c C-l`.
For `zsh` put this in your `.zshrc`:
```zsh
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
alias clear='echo -n  "\e]51;E(vterm-clear-scrollback)\e\\";tput clear'
fi
```
For `bash` put this in your `.bashrc`:
```bash
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
function clear(){
printf  "\e]51;E(vterm-clear-scrollback)\e\\";
tput clear;
}
fi
```
=> clear scrollback

vterm.el
This PR improves handling of shift-space. I find that I often hold down shift after typing special characters, like `!`. Using `emacs-libvterm`, <kbd>S-SPC</kbd> currently sends an escape sequence that ends up being displayed on the line.
With the changes in this PR, holding shift will send a space normally, like in other terminal programs. macOS's Terminal.app and iTerm2 both do this, so it seems like standard behavior.
=> Fix shift-space behavior

vterm-module.c, vterm-module.h, vterm.el
#56 
vterm enable `compilation-shell-minor-mode` by default.
even you change your working directory, `next-error` `previous-error` still
can find out the corresponding source code.
For `zsh` put this in your `.zshrc`:
```zsh
vterm_prompt() {
print -Pn "\e]51;A$(pwd)\e\\";
}
PROMPT=$PROMPT'%{$(vterm_prompt)%}'
```
please use `PROMPT`, and do NOT use `chpwd` or `preexec`,
unless you don't want to using `compilation-shell-minor-mode`.
The working directory of lines after a new prompt  need be updated .
For bash 
```bash
vterm_prompt_end(){
printf "\e]51;A$(pwd)\e\\"
}
PS1=$PS1'$(vterm_prompt_end)'
```
this is ready to be reviewed ,but need more testing before merge.
=> Support compilation shell minor mode

vterm.el
I find it useful to send <kbd> C-\ </kbd> and <kbd>C-g</kbd> to the terminal, for instance to control tmux and exit from `fzf` completions. This MR adds keybindings to send those key combinations.
=> WIP: add C-\, C-g

vterm-module.c
Check for NULL pointer before using.  And return Qnil if directory is NULL.
=> fix vterm--get-pwd crash

vterm.el
- `M-f` Move forward a word.
- `M-b` Move backward a word.
- `M-d` Kill from the cursor to the end of the current word
=> Add vterm-send-meta-{b,d,f} and bind M-{b,d,f}

vterm-module-make.el, vterm.el
Currently, on each update vterm recompiles the module disregarding the general system settings and also fetches libvterm. This is very annoyng and requires integration of vterm into a system package manager.
When installing from an external package manager, it makes no sense to even have `vterm-module-compile` available unless it is kept aligned with system-wide settings. Keeping it aligned, however, essentially requires patching the package twice: patching command string in elisp, and introducing the same options on a more general level, which is a very unwelcome redundancy.
It's best if elisp build infrastructure can be disregarded completely; for that, `vterm.el` has to be split and all build-related stuff should go to its own elisp module. It is also beneficial due to the fact that …
=> Separate elisp code that builds external dependency and the rest of elisp code

vterm.el
I sometimes want to know if a command run in vterm has successfully exited.
More specifically, I have the following function to run an interactive program inside vterm:
```emacs-lisp
(defun akirak/run-interactive-shell-command (command &optional name)
(interactive "s")
(let ((buffer (generate-new-buffer (or name "*vterm*"))))
(with-current-buffer buffer
(let ((vterm-shell command))
(vterm-mode))
(pop-to-buffer buffer))))
```
And I want to know the exit code of the command.
Since Emacs provides [sentinels](https://www.gnu.org/software/emacs/manual/html_node/elisp/Sentinels.html) to track status changes in processes, it is technically possible to get the exit status of a process. However, vterm drops event information from sentinels rather than pass it to functions in …
=> Breaking change: Pass sentinel events to exit functions

CMakeLists.txt
libvterm's Makefile appears to require GNU-Make, which is available on
tFreeBSD from the gmake port as 'gmake' command. The 'make' command
from FreeBSD's base installation won't accept the Makefile.
My "fix" works only if the user installs GNU-Make on their system and it's only for FreeBSD, but I think the same problem exists on OpenBSD, too.
=> fixed: libvterm's build command on FreeBSD

README.md, vterm.el
`vterm-kill-buffer-on-exit` is a new flag that can be set to `t` to kill buffer when the associated process is terminated.
=> Add vterm-kill-buffer-on-exit custom variable

elisp.c, elisp.h, vterm-module.c, vterm.el
1. Can set font for vterm  buffer by custom vterm-font-default .
2. Rendered properly when  font resizing. #162 is related 
3.  `line-spacing' needn't set to nil now.
=>  Rendered properly when  font resizing and add face vterm-font-default

vterm.el
bind vterm-clear on `C-l'.
when  vterm-clear-scrollback is nil
`C-l' will clear screen.
`C-uC-l' will clear both screen and scrollback.
when  vterm-clear-scrollback is not nil
`C-l' will clear both screen and scrollback.
`C-uC-l' will clear screen.
#218
=> add defcustom  vterm-clear-scrollback and command vterm-clear.

vterm.el
The usage of switch-to-buffer in packages is discouraged. See, https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28645#25
This commits addresses issue #180 and should avoid the point to jump around unexpectedly when new buffers are opened in unusual ways or with unusual configurations.
=> Substitute switch-to-buffer with pop-to-buffer-same-window

README.md
The Guix package was added in https://git.savannah.gnu.org/cgit/guix.git/commit/?id=3d11114d229035440b49dccd964a2efa7ad5874f.
----
#
=> Add instructions for installation via GNU Guix

CMakeLists.txt, README.md, vterm-module-make.el
This PR implements the improvements discussed in #253 and #240. Namely:
1. By default, vterm uses libvterm pulled from GitHub, now updated to 0.1.3
2. Users can change this behavior by customizing the variable `vterm-module-compilation-flags`
3. We check that `cmake` is available before compiling. If it is not available, we throw an error
4. We check that libtool is available (during compile-time), if not, we inform the user
5. We implement a workaround to avoid changing the `default-directory`, "fixing" #243 
If this PR is merged, #240 and #253 will be closed (without being merged).
@fbergroth, are you interested in reviewing this PR?
=> Update build system

README.md
according to https://github.com/akermu/emacs-libvterm/issues/188#issuecomment-585892079,
and tested locally with `oh-my-zsh` on my mac.
this should be the correct configuration for zsh
=> Update zsh directory track config

elisp.c, elisp.h, vterm-module.c, vterm-module.h, vterm.el
This commit fixes up the newlines that were inserted for wrapping using the same
approach as term.el does. It does so by adding a property to the '\n' chars that
were inserted as a result of wrapping the terminal. When killing a region text
will be passed through the filter-buffer-substring-function
vterm--remove-fake-newlines removing the wrapped new lines by looking for the
'vterm-line-wrap property and removing the char that corresponds.
If this change set is not up to project standards please work with me to correct
any issues you find.
=> This commit fixes the newlines when copied and pasted.

README.md, elisp.h, vterm-module.c, vterm-module.h, vterm.el
just like `term-next-prompt` and `term-previous-prompt` in `term.el`
```
(define-key vterm-copy-mode-map (kbd "C-c C-n")        #'vterm-next-prompt)
(define-key vterm-copy-mode-map (kbd "C-c C-p")        #'vterm-previous-prompt)
```
=> reimplements vterm--get-prompt-point with text property and bind vterm-next/previous-prompt

vterm-module-make.el, vterm.el
Hi, I'm using this package as a submodule (using borg package manager rather than installing via package.el) and found some issues. See each commit.
- Do not compile vterm when loading vterm-module-make
I don't think compilation should run when just loading vterm-module-make. Explicitly calling compile from vterm.el makes more sense.
- Always compile when calling vterm-module-compile
If you have an outdated vterm-module.so, you'll want to be able to recompile it. `(require 'vterm-module nil t)` is already essentially the same check. I want to call vterm-module-compile whenever I update this submodule, but currently it does nothing if vterm-module.so exists.
Then I went loose and fixed byte compilation:
- Add declarations to quiet byte compiler
- Remove unused code
- Inline vterm-bind-key …
=> Fix some packaging issues

vterm-module.c, vterm-module.h, vterm.el
- `vterm-disable-underline` to resemble xterm's "XTerm\*underLine: off"
- `vterm-color-underline` to resemble xterm's "XTerm\*colorULMode",
"XTerm\*colorUL"
- `vterm-disable-inverse-video` to disable `:inverse-video`
- `vterm-color-inverse-video` to resemble xterm's "XTerm\*highlightColor"
=> [add] Custom faces for cells with underline/inverse-video attrs

vterm-module.h, vterm.el
In this PR I add [makem.sh](https://github.com/alphapapa/makem.sh) to this project. 
`makem` provides a simple way to use GitHub actions to test and lint the code in a sandboxed environment. At the moment, I envision using `makem` for linting, but it would be great if we added tests too. Notice, this package would not be accepted in MELPA in the current state. 
It is necessary that we improve the documentation of the code, and I hope that `makem` will help us in this direction. I am working on improving the documentation on the elisp side. At the moment, I am just trying to have a minimum of documentation for everything, but I am planning to go deeper and have more comprehensive docstrings.
I think that from now on we shouldn't merge PR if they add features that are not thoroughly …
=> Cleanup code to reduce linter/compiler errors

README.md, vterm.el
The option `vterm-clear-scrollback` has a non-descriptive name that clashed with a function named in the same way.
=> Rename vterm-clear-scrollback to vterm-clear-scrollback-when-clearing

vterm.el
Addresses #298.
It makes no sense to change major-mode. So we prevent users from doing that. A similar (more drastic) approach is followed by EXWM.
=> Prevent change of major-mode

README.md, vterm.el
`vterm-title-functions` main purpose is to rename vterm buffers. But, at the moment, it is overly complicated. This PR substitutes `vterm-title-functions` with a new simpler interface that automatically renames buffers with a format string defined by the user. Now, users can simply set `vterm-buffer-name-string` to `%s` to have buffers named after the title (if properly configured shell-side).
If I am missing some use of `vterm-title-functions`, please let me know.
=> Remove, vterm-title-functions, add vterm-buffer-name-string

README.md, vterm.el
`vterm` should ask users the permission to compile the module, instead of doing it without any warning. To avoid asking every time the question, the variable `vterm-always-compile-module` compiles the module without asking (that would be the current behavior).
=> Ask users for permission to compile module

CMakeLists.txt, README.md
It is mainly for `vterm-module-cmake-args` when it is just installed, it is not available. So I want to use this variable to let `vterm` use the system `libvterm` package. This is done through `CMakeLists.txt`.
=> Automatic detection for system libvterm first

vterm.el
The `vterm--term` variable contains a pointer to the associated Term. It has to be defined and valid for low-level functions to work, failure to do so leads to a segmentation fault. It may fix #316.
=> Check for vterm--term pointer

README.md, vterm.el
1. Change the default value of `vterm-kill-buffer-on-exit` to t. 
2. Add comparison between vterm and other terms and shells. Fixes #14. 
3. Change `vterm-use-vterm-prompt` to `vterm-use-vterm-prompt-detection-method`. Addresses #306.
4. Update package description and commentary
5. Expand other documentation
=> Update documentation and docstrings

vterm.el
When the native-compile feature is enabled, `locate-library` returns the path to
the compiled (`.eln`) file rather than the `.el` or `.elc` that would otherwise
be expected. Then `vterm-module-compile` runs the compilation from that
subdirectory and can't find the expected files.
`find-library-name` always returns the `.el` file location.
Example error:
```
CMake Error: The source directory "/Users/user/.emacs.d/straight/build/vterm/eln-x86_64-apple-darwin19.5.0-89a730c11dec204e" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
```
After this change the compilation files are found as expected.
=> With the native-compile feature enabled, properly find build dir

vterm.el
Reverts akermu/emacs-libvterm#373.
I forgot to squash the commits!
=> Revert "With the native-compile feature enabled, properly find build dir"

vterm.el
The default key bindings should be defined inside the `defvar` form
that defines the respective keymap.
When defining the key bindings separately then reloading the defining
library (e.g. using `eval-buffer`) would discard user customizations
unintentionally, while _intentionally_ discarding all customizations
using `eval-defun` on the `defvar` form becomes impossible.
The `defvar` form has to come before the respective mode is defined,
otherwise `define-derived-mode` would define the keymap, and the
subsequent `defvar` form would fail to set the default value.
This also includes the commit from my previous pull-request, #382,
I can change that if desired.
=> Define key bindings inside defvar forms

README.md, etc/emacs-vterm-bash.sh, etc/emacs-vterm-zsh.sh, etc/emacs-vterm.fish
Combining the described configurations into separate files makes it easier for users to configure their shell. Also, package managers could automatically install them system-wide, see for example [a Gentoo ebuild](https://github.com/gentoo/guru/blob/master/app-emacs/vterm/vterm-20200504.544.ebuild).
=> Add shell configs

vterm.el
This reverts commit a43f9702007436bc243673164c405e37c77ed1f3.
=> Revert "avoid garbling of certain multibyte characters ."

vterm.el
- This change prevents the region and point location from being lost on resize,
and a whole slew of other weird behaviors.
=> Don't resize while in copy mode.

CMakeLists.txt
BSD make barfs on the libvterm Makefile that gets pulled in if you try to build without the system libvterm (i.e. `cmake -DUSE_SYSTEM_LIBVTERM=no ..`) This adds rules for OpenBSD and NetBSD so that they use GNU make.
=> Add Cmake rules for OpenBSD & NetBSD

CMakeLists.txt, vterm-module.c, vterm-module.h
#403 
should fix  #389 
Edit: should ready to be reviewed.
=> upgrade libvterm

README.md, elisp.c, elisp.h, vterm-module.c, vterm-module.h, vterm.el
this pull request need merged after #404 
Add option: `vterm-enable-manipulate-selection-data-by-osc52`
Vterm support copy text to emacs kill ring and system clipboard by using OSC 52.
See https://invisible-island.net/xterm/ctlseqs/ctlseqs.html for more info about OSC 52.
For example: send 'blabla' to kill ring(and clipboard): printf "\033]52;c;$(printf "%s" "blabla" | base64)\a"
tmux can share its copy buffer to terminals bysupporting osc52(like iterm2 xterm),
you can enable this feature for tmux by :
set -g set-clipboard on         #osc 52 copy paste share with iterm
set -ga terminal-overrides ',xterm*:XT:Ms=\E]52;%p1%s;%p2%s\007'
set -ga terminal-overrides ',screen*:XT:Ms=\E]52;%p1%s;%p2%s\007'
The clipboard querying/clearing functionality offered by OSC 52 is not implemented here,
And …
=> Support osc 52 Manipulate Selection Data. #343

README.md
Related to #216 
I ran into a the following error while installing on Ubuntu 20.04 today, and wanted to update the document with the steps required to get it working:
``` sh
Errors were encountered while processing:
/tmp/apt-dpkg-install-RVK8CA/064-emacs27-common_27.1~1.git86d8d76aa3-kk2+20.04_all.deb
```
=> Ubuntu 20.04

vterm.el
In b1ff04d43920927db36eef15e5bfa0f7a844ba47 `term--exclude-keys` got an additional argument but I forgot to update this caller accordingly.
=> Fix customizing vterm-keymap-exceptions

README.md, vterm-module.c, vterm.el
emacs-libvterm creates lots of text properties on each character. I propose to minimize them. In particular, with this patch `vterm--get-color` can return nil when the default face should be used, which is in general the case for most characters.
=> Minimize text properties

README.md, etc/emacs-vterm-bash.sh
=> Use bash variables instead of escape sequences

vterm.el
Fix [1: beda920], whose commit message was quite accurate.  That
commit used `defvar-local` in the believe that this would define a
variable with some sort of local scope, which would be the correct
thing to do, but unfortunately that's not what this macro does at
all. (Please refer to the Emacs Lisp manual for more information.)
Luckily we don't need a variable at all, but if we did, then we
would use `let` to introduce it.
Furthermore `system-type`'s value is a symbol not a string, wrapping
the condition in `not` needlessly complicates things, and the lines
are too long.
1: beda920037a36084d0d312cf2d1133314f68feba
[Fix] Gross hack to work around problem on *BSD
=> Fix a recent gross hack

vterm-module.c, vterm.el
`vterm-delete-region` is  `delete-region` for `vterm.
After this pull request is merge.
It  would make it more  comfortable for `evil-mode` user .
related issues #313 #160  #156 
I don't know where to put these evil-mode related code, so just put it here, Any suggestions?
```
(defun vterm-evil-insert ()
(interactive)
(vterm-goto-char (point))
(call-interactively #'evil-insert))
(defun vterm-evil-append ()
(interactive)
(vterm-goto-char (point))
(call-interactively #'evil-append))
(defun vterm-evil-delete ()
"Provide similar behavior as `evil-delete'."
(interactive)
(let ((inhibit-read-only t)
)
(cl-letf (((symbol-function #'delete-region) #'vterm-delete-region))
(call-interactively 'evil-delete))))
(defun vterm-evil-change ()
"Provide similar behavior as `evil-change'."
(interactive)
(let …
```
=>  add some function vterm-delete-region and vterm-goto-char

vterm.el
`vterm-yank` broke after the commit https://github.com/akermu/emacs-libvterm/commit/f21d0dd1abc26ae447736c978cb2ea942627cd90 due to wrong `symbol-function` call (`insert` instead of `insert-for-yank`)
This pull request fixes the issue 🏆
=> vterm-yank: fix wrong symbol-function call

README.md, elisp.c, elisp.h, vterm-module.c, vterm-module.h, vterm.el
This patch also adds support for cursor blink.
VIM emits these ANSI escape sequences in insert mode:
```
\x1b[?25h   show cursor
\x1b[?25l   hide cursor
```
You may add these to ~/.vimrc to verify it:
```
" https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes
" Cursor settings:
"  1 -> blinking block
"  2 -> solid block 
"  3 -> blinking underscore
"  4 -> solid underscore
"  5 -> blinking vertical bar
"  6 -> solid vertical bar
let &t_SI="\e[5 q"
let &t_SR="\e[3 q"
let &t_EI="\e[1 q"
```
@jixiuf
=> fix cursor type after hide cursor and show again

vterm.el
So the buffer is quittable by pressing q, and the compilation warnings and errors are navigable
=> Put module compilation buffer in compilation mode

vterm.el
Vterm-yank does not copy from the system clipboard that is supported
via xterm.el. This patch fixes it.
=> Fix xterm-paste in vterm.

vterm.el
This `require` should have been added in #485.
=> Silence byte-compiler

vterm.el
Inspired by emacs/lisp/term.el:term-send-raw-string, fixed issue
https://github.com/akermu/emacs-libvterm/issues/489.
=> deactivate mark on key input

README.md, etc/emacs-vterm-bash.sh, etc/emacs-vterm-zsh.sh, etc/emacs-vterm.fish
tmux requires that `TERM` is set to `screen*` or `tmux*` for subshells running inside tmux. See https://github.com/tmux/tmux/wiki/FAQ
Using this, I was able to change the `vterm_printf` passthrough switch such that it is not activated if Emacs and vterm are running **within** a tmux session. The passthrough still functions for running tmux within Emacs and vterm.
I have not yet tested the changes to the Fish shell-side configuration. 
Closes #443.
=> Fix vterm_printf tmux escape sequence pass through

vterm.el
=> Make `vterm--self-insert` function send key that corresponds to current input method

vterm.el
As I still experience issue #202, I have looked into the code of `self-insert-command` to look for any differences in how translated keys are handled. I’ve found that `self-insert-command` uses `last-command-event` to determine the pressed key, while `vterm--self-insert` and `vterm-send-key` use `last-input-event`. I’ve changed the `vterm` functions to use `last-command-event`, which makes them handle translated keys properly and fixes the issue for me.
To highlight the differences (as far as I understand them), let’s take a look at `<kp-add>`.
1. The user presses `<kp-add>`.
2. `last-input-event` is set to `<kp-add>`.
3. No command is bound to `<kp-add>`.
4. `<kp-add>` gets translated to `+` using `key-translation-map`.
5. The command `self-insert-command`/`vterm--self-insert` is bound …
=> Handle translated keys correctly and fix keypad keys.

vterm.el
CMake generates build files for the system defined as `$CMAKE_GENERATOR`. For instance, I use `ninja` as my default generator. Since CMake supports multiple build systems, the following should normally be used:
```sh
cmake ..
cmake --build .
```
`vterm-module-compile` instead assumes that CMake generates Makefile, and runs `make` directly, which will fail if the user has specified a different `CMAKE_GENERATOR`.
However, using `Ninja` fails in our case because `libvterm` is a Makefile project, and Ninja does not know how to build it. This entire thing can be resolved by enforcing Make with CMake:
```sh
cmake -G 'Unix Makefiles' ..
make
```
=> vterm-module-compile: Enforce 'Unix Makefiles' for CMake

vterm.el
After commit 060910425b77660503ec248fb1c383df40eec758, setting
vterm-module-cmake-args without including a leading space will typically
result in an error like:
CMake Error: Could not create named generator Unix Makefiles-DUSE_SYSTEM_LIBVTERM=yes
If vterm-module-cmake-args is an empty string (the default) everything
still works.
Fix it by adding a space between the cmake generator name and
vterm-module-cmake-args.
=> Add missing space before vterm-module-cmake-args

vterm.el
The default of USE_SYSTEM_LIBVTERM changed in commit
78d4883ae13054c26440a79a876929a8617560b3. Update the docstring to
describe the new behavior.
=> Fix USE_SYSTEM_LIBVTERM description in docstring

vterm.el
`C-M-f/b` move cursor forward/backward an S-expression in buffer, but not in vterm, which could cause confusion.
So we exclude those keys. (By binding them to `'ignore`)
=> Exclude "C-M-" "C-M-S-" keys

vterm.el
A WIP attempt at implementing https://github.com/akermu/emacs-libvterm/issues/522 .
(find-file "/ssh:foo@bar.example.com:")
(vterm)
Observe that vterm has a remote shell open (woo!).
Then type `top`, and observe it correctly renders a remote `top` process (woo!).
=> WIP: Support opening a vterm over TRAMP/SSH

README.md
If `PROMPT_COMMAND` is empty, the original would leave `;vterm_set_directory` as its value, giving error
```
[michael@contessa emacs-libvterm]$ PROMPT_COMMAND=";vterm_set_directory"
bash: PROMPT_COMMAND:16: syntax error near unexpected token `;'
bash: PROMPT_COMMAND:16: `;vterm_set_directory'
```
=> Correctly append to `PROMPT_COMMAND` for bash.

vterm.el
This fixes incorrect terminal width when using `vterm-other-window`.
Vterm sets terminal width in `vterm-mode` by calling `window-body-width`.
If we call `vterm-mode` before terminal window creation,
it would actually get previous window's width.
=> Fix incorrect terminal width when using vterm-other-window

vterm.el
This patch allows saving bookmarks in vterm mode. It saves the
current buffer name, as well as the current directory.
When asked to restore a bookmark, it will create a new vterm buffer
if needed, and navigate to the previous directory if the custom
variable vterm-bookmark-check-dir is set to non-nil.
This can be quite convenient for people who constantly have several
vterm buffers with different names/dirs for different needs.
=> Support bookmarks in vterm.

README.md
Debian 11 is now stable and currently has 0.1.4-1 of libvterm-dev in packages.
=> Update documentation for Debian versions

CMakeLists.txt, vterm-module.h
Fixes https://github.com/akermu/emacs-libvterm/issues/559
As commented in https://github.com/akermu/emacs-libvterm/issues/559#issuecomment-992681062, emacs crashes when loading vterm-module.so because the address of `Qt` is incorrectly resolved to the read-only symbol in `emacs` binary. I can verify this with `LD_DEBUG=all`:
```
75570:     binding file .../.emacs.d/straight/build/vterm/vterm-module.so [0] to ./src/emacs [0]: normal symbol `Qt'
```
This PR hides all symbols except two necessary ones, so that the symbols like `Qt` will be resolved correctly.
I'm still unclear about the root cause: I thought `RTLD_LOCAL` should be the default behavior for `dlopen` so this should not happen; It's also strange that this only happens when building with `--with-xwidgets`, maybe loading xwidgets …
=> Do not export unnecessary symbols in dynamic library

README.md, vterm.el
Read next input event and send it to the libvterm.
This is useful for controlling an emacs session within emacs-libvterm.
=> Add send-next-key function

vterm.el
Hi,
When using `vterm` together with `zsh` the `dirhistory` plugin does not work due to lacking bindings for the following keys:
- `M-<up>`
- `M-<down>`
- `M-<left>`
- `M-<right>`
Thanks for the this great terminal!
=> Add vterm-send-meta<up,down,left,right> functions and keybindings

vterm.el
Else the byte-compiler gets worried.
=> Declare variable before first use

vterm.el
see https://invisible-island.net/xterm/ctlseqs/ctlseqs.html says 
ESC =     Application Keypad (DECKPAM).
when run ghci it echo "\e=Prelude>",
I think `\e=` should be treat as  control seq?
=> try fix #598.  treat `ESC =` as control seq.

README.md, vterm.el
After #619  is merged, commands like  `vterm-send-C-[a-z]` `vterm-send-M-[a-z]` and 
`vterm-send-{up/down/left/right/prior/next/meta-dot/meta-comma/ctrl-slash}` are useless for vterm.el.
But it is a breaking change for other packages,  so I am not sure should I merge this PR or not.
@Sbozzolo  @Inc0n
=> delete all unused command like vterm-send-C-[a-z] vterm-send-M-[a-z].

vterm.el
Title says it all, it is listed a number but expects a boolean
=> Fix type for vterm-clear-scrollbark-when-clearing

README.md, etc/emacs-vterm.fish
This commit improves documentation for [vterm-buffer-name-string](https://github.com/akermu/emacs-libvterm#vterm-buffer-name-string).
Fish has a utility function [`prompt_pwd`](https://fishshell.com/docs/current/cmds/prompt_pwd.html), which prints pwd suitable for prompt.
=> Use `prompt_pwd` to format `/home/myuser/mydir` as `~/mydir`

CMakeLists.txt, vterm-module.c, vterm-module.h
Add support for the `sb_clear` callback, which enables terminal apps to clear the scrollback of the terminal.  Support for this callback was added in vterm 0.3, so I've updated the SHA to download that version in the auto-download case.  This is particularly important to run terminal apps like `jest` where the scrollback is often cleared for clarity
=> Support clearing scrollback from terminal apps

vterm.el
This commit enables C-a and C-e to be used with shift modifer to select region to start of line and end of line, if `shift-select-mode` is enabled.
This is done by putting "^" into interactive, for more information see, https://www.emacswiki.org/emacs/ShiftSelectMode.
Additionally, I would recommend to bind M-w (king-ring-save) to `vterm-copy-mode-done` also, which is the default key bind to region save, this change I haven't introduce in this commit. I use this bind all the time, and had to manually quite copy-mode using C-c C-t, instead of using return.
I mentioned the above here, since this commit is about introducing better integration between vterm and emacs.
=> Enable selection for commands in copy-mode

vterm.el
The environment of each project may be different, and "dir_locals.el" provides an excellent way to configure each project separately. This patch enables config project environment by using "vterm-environment."
=> config vterm-environment in dir_locals

vterm.el
Fixes: https://github.com/akermu/emacs-libvterm/issues/567
If emacs-vterm is started on a remote, use the same shell as TRAMP. That will guarantee that the shell exists on the remote.
A shell could be chosen using `vterm-tramp-shells', but it tied to a specific TRAMP method. However, the same method (ssh) could be used to connected to different remotes, each with different default shell. So, we could use TRAMP to get the shell on per-remote basis.
=> Use same shell as TRAMP on remotes.

vterm.el
When the buffer is empty,
```lisp
(get-text-property (1- (point)) 'vterm-line-wrap)
```
throws an error.
This situation happens when the empty string is passed as argument to
`vterm--filter-buffer-substring`.
=> Fix vterm--remove-fake-newlines when in an empty buffer

vterm.el
I didn't find an easy way to determine whether the cursor is in the last prompt line or what the prompt line number even is. And one cannot assume the prompt line is the last line of the buffer beacuse vterm is basically a rectangle filling the whole buffer. As a consequence `(line-number-at-pos (point-max))` _doesn't work_ because `(point-max)` _doesn't work_.
With this patch, it is possible to find the prompt line using:
(line-number-at-pos (vterm--get-beginning-of-line
(vterm--get-cursor-point)))))
And in case the command in prompt is long and wraps into multiple lines, its end can be found using:
(line-number-at-pos (vterm--get-end-of-line
(vterm--get-cursor-point)))))
=> Allow to find beginnig and end of line from a specific point

vterm.el
Without this patch, I am able to click somewhere below the last prompt line and move the cursor there. I don't think this was an intended feature, it feels more like a weird quirk.
We don't have any function telling us the point or line number of the last prompt, and it doesn't seem to be easy to implement, so I needed to workaround this.
=> Don't allow moving cursor below the last prompt via mouse

README.md, elisp.c, elisp.h, vterm-module.c, vterm.el
So far, vterm has been using `:foreground` attribute of its faces for regular colors (0-7), and `:background` attribute for bright colors (8-15). This is counter-intuitive and limits customization possibilities: In particular, it has been impossible to specify different color values, depending on whether the ANSI index is used for background or foreground.
Emacs' `ansi-color-*` and `term-color-*` faces allow specifying colors in this way by setting the `:foreground` and `:background` attributes respectively, but have been missing the bright half of the palette. The palette has been completed in Emacs 28 with new faces `ansi-color-bright-*` and `term-color-bright-*`.
This PR extends the vterm color handling with new bright color faces similarly to `term.el` and `ansi-color.el` and adjusts …
=> Allow different foreground/background colors for same ANSI index

vterm.el
When using emacs in a terminal the initial column count is off by one.  This only happens on initial creation of a vterm.  After re-sizing the terminal the right column count is used. 
Replacing `windows-body-width` with `windows-max-chars-per-line` resolve this issue. This is mostly driven because the last column when in terminal mode is not really usable. This change does not seem to affect the gui version emacs in any way. 
Rendering in terminal emacs without fix: 
Rendering in terminal emacs with fix: 
Rendering will fix its self once you resized the window, with something like M-x. You can also inspect the changes in col values before and aver resize with `echo $(tput cols)`.
=> Ensures the starting col is the same as later calculated

vterm-module.h
This allows the user to select the scrollback buffer size via compiler preprocessor defines (instead of having to edit the source file) and falls back to the statically configured `SB_MAX` if there is no `-DSB_MAX=$VALUE` given.
=> Support overriding SB_MAX at compile-time with -D defines

vterm-module.c, vterm.el
When use [lf](https://github.com/gokcehan/lf) to list files, emacs-libvterm may read partial multi-byte character, for example:
$ echo -n '招聘' | hexdump -C
00000000  e6 8b 9b e8 81 98
; get "招", control sequence and partial character
(vterm--filter process "\xE6\x8B\x9B\e[14;111H\xE8")
; now full "聘"
(vterm--filter process "\x81\x98")
This will send "\xE8" to libvterm which is not a full character.
=> don't garble partial multi-byte character after control sequence

vterm.el
This pull request fixes the issue #731 where the $ symbol appears at the end of some lines.
It usually happens when the user calls `text-scale-increase` or `text-scale-decrease` to change the font size.
=> Fixes #731: Prevent the display of truncation characters ($)

README.md
This pull request updates README.md:
- Replaces `clear` with a POSIX-compliant function,
- Fixes the ShellCheck warning [SC2235](https://www.shellcheck.net/wiki/SC2235) in `vterm_printf()` ("Use { ..; } instead of (..) to avoid subshell overhead")
> You appear to be using (..) to group test commands. This creates a subshell, making it unnecessarily slow. Avoid this by using { ..; } to group.
> Be careful to note that unlike (..), this requires both a space after the { and a semicolon before the }.
> For example, (cmd), (cmd;) and ( cmd ) are all valid, but {cmd}, {cmd;} and { cmd } are all syntax errors because they lack either or both of the spaces and semicolon. The correct form is { cmd; }
=> Fix warnings in `vterm_printf()` and `clear` sh/bash shell functions in README.md

README.md, vterm.el
For remote machines, let vterm start with the default login shell of the remote host.
This can be configured by specifying a the symbol 'login-shell as SHELL in vterm-tramp-shells. The current default behavior is not changed.
In addition, allow "*" as a wildcard method in vterm-tramp-shells.
This was requested in #655
=> Allow using the default login shell for remote connections

README.md
It seems there is demand for making this work on Windows, so would be nice if the text that says it doesn't work would be linked to the issue that contains the research. This will allow interested people *(if such appear)* to avoid researching everything from scratch, but rather basing their work on the information already done by others.
This came up on SE: https://emacs.stackexchange.com/questions/82896/error-use-package-vterm-catch-searching-for-program-no-such-file-or-direct/82909#82909
=> README: link the issue of running on Windows
